### ISSUE TITLE
error while running roslaunch aama_sim sim_controller.launch

### ISSUE THREAD

**Issue by haliliceylan** [micss-lab/AAMA-sim#17]
```
halil@halil-OptiPlex-7020:~/catkin_ws/src$ roslaunch aama_sim sim_controller.launch
... logging to /home/halil/.ros/log/45378480-0e94-11ee-920c-f720ba75f0f1/roslaunch-halil-OptiPlex-7020-100267.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://halil-OptiPlex-7020:37935/

SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /
    sensor_controller (aama_sim/sensor_controller.py)
    sim_controller (aama_sim/simulation_controller.py)

ROS_MASTER_URI=http://localhost:11311

process[sim_controller-1]: started with pid [100286]
process[sensor_controller-2]: started with pid [100287]
Traceback (most recent call last):
  File "/home/halil/catkin_ws/devel/lib/aama_sim/sensor_controller.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/halil/catkin_ws/src/AAMA-sim/src/aama_sim/simulation_controller/sensor_controller.py", line 35, in <module>
    a = SensorController()
  File "/home/halil/catkin_ws/src/AAMA-sim/src/aama_sim/simulation_controller/sensor_controller.py", line 17, in __init__
    self.rabbitmq_comm = RabbitCommunication()
  File "/home/halil/catkin_ws/src/AAMA-sim/src/aama_sim/comm_interface/rabbitmq_interface.py", line 16, in __init__
    self.connect()
  File "/home/halil/catkin_ws/src/AAMA-sim/src/aama_sim/comm_interface/rabbitmq_interface.py", line 25, in connect
    self.connection = pika.BlockingConnection(
  File "/home/halil/.local/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/home/halil/.local/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.ProbableAccessDeniedError: ConnectionClosedByBroker: (530) "NOT_ALLOWED - access to vhost '/' refused for user 'dogu'"
Traceback (most recent call last):
  File "/home/halil/catkin_ws/devel/lib/aama_sim/simulation_controller.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/halil/catkin_ws/src/AAMA-sim/src/aama_sim/simulation_controller/simulation_controller.py", line 30, in <module>
    a = SimulationController()
  File "/home/halil/catkin_ws/src/AAMA-sim/src/aama_sim/simulation_controller/simulation_controller.py", line 17, in __init__
    self.rabbitmq_comm = RabbitCommunication()
  File "/home/halil/catkin_ws/src/AAMA-sim/src/aama_sim/comm_interface/rabbitmq_interface.py", line 16, in __init__
    self.connect()
  File "/home/halil/catkin_ws/src/AAMA-sim/src/aama_sim/comm_interface/rabbitmq_interface.py", line 25, in connect
    self.connection = pika.BlockingConnection(
  File "/home/halil/.local/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/home/halil/.local/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.ProbableAccessDeniedError: ConnectionClosedByBroker: (530) "NOT_ALLOWED - access to vhost '/' refused for user 'dogu'"
[sim_controller-1] process has died [pid 100286, exit code 1, cmd /home/halil/catkin_ws/devel/lib/aama_sim/simulation_controller.py __name:=sim_controller __log:=/home/halil/.ros/log/45378480-0e94-11ee-920c-f720ba75f0f1/sim_controller-1.log].
log file: /home/halil/.ros/log/45378480-0e94-11ee-920c-f720ba75f0f1/sim_controller-1*.log
[sensor_controller-2] process has died [pid 100287, exit code 1, cmd /home/halil/catkin_ws/devel/lib/aama_sim/sensor_controller.py __name:=sensor_controller __log:=/home/halil/.ros/log/45378480-0e94-11ee-920c-f720ba75f0f1/sensor_controller-2.log].
log file: /home/halil/.ros/log/45378480-0e94-11ee-920c-f720ba75f0f1/sensor_controller-2*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

I checked credentials, They are working.

![image](https://github.com/micss-lab/AAMA-sim/assets/33789758/4cbaa937-19a6-48a0-a6a2-a99f3ea88d91)

**Comment by haliliceylan** [comment]
https://github.com/micss-lab/AAMA-sim/blob/main/README.md?plain=1#L63

**Comment by DogukanAltay** [comment]
`- Create a new user with admin privilages with below ID and password.
    - ID: dogu
    - Password: dogu
` You can resolve the issue inside the RabbitMQ management page under Admin
You should give "\" to all hosts and permissions like the admin user that should resolve it

**Comment by DogukanAltay** [comment]
Otherwise you can enter the RabbitMQ docker and execute the following command.
`rabbitmqctl set_permissions -p / $RABBITMQ_USER  ".*" ".*" ".*" ;`

**Comment by haliliceylan** [comment]
I will try and let you know

**Comment by haliliceylan** [comment]
![image](https://github.com/micss-lab/AAMA-sim/assets/33789758/441bfe39-0b1f-4f0a-827c-b91bcd185edb)

Yea, its working rn !
